import type { CuratedShelf, Product } from "./types";

const img = (id: string) => `https://images.unsplash.com/${id}?auto=format&fit=crop&w=1200&q=82`;

export const demoProducts: Product[] = [
  {
    id: "p1",
    title: "Fictional Demo: Dublin Docklands History, Annotated Paperback",
    slug: "dublin-docklands-history-annotated-paperback",
    category: "BOOKS",
    subcategory: "Irish History",
    creator: "M. Keane",
    publisher: "Liffey House Press",
    isbn: "9780000001001",
    sku: "BMGX-DEMO-0001",
    priceMinor: 950,
    shortDescription: "A clean second-hand Irish history paperback with pencil notes on several pages.",
    description: "Fictional demo inventory. A readable paperback study of Dublin's docklands, photographed and described as an individual second-hand copy.",
    conditionGrade: "GOOD",
    conditionReport: "Light spine creasing, clean cover edges, pencil annotations on pages 42-57.",
    included: ["Paperback book"],
    missing: [],
    shelfLocation: "Books / Irish History",
    quantity: 1,
    inventoryState: "PUBLISHED",
    isFeatured: true,
    isStaffPick: true,
    isRare: false,
    imageUrl: img("photo-1543002588-bfa74002ed7e"),
    gallery: [img("photo-1543002588-bfa74002ed7e"), img("photo-1516979187457-637abb4f9353")]
  },
  {
    id: "p2",
    title: "Fictional Demo: The Glass Signal, Signed First Printing",
    slug: "the-glass-signal-signed-first-printing",
    category: "RARE_COLLECTIBLE",
    subcategory: "Signed Fiction",
    creator: "Elaine Byrne",
    publisher: "North Quay Editions",
    isbn: "9780000001002",
    sku: "BMGX-DEMO-0002",
    priceMinor: 6400,
    shortDescription: "Signed fictional collectible book, clearly marked as demo stock.",
    description: "Fictional demo inventory. Staff notes identify a visible signature on the title page; authenticity is not independently certified.",
    conditionGrade: "STAFF_REVIEWED_COLLECTIBLE",
    conditionReport: "Sharp boards, mild jacket rubbing, visible inscription to title page.",
    included: ["Hardback", "Dust jacket"],
    missing: [],
    shelfLocation: "Cabinet / Rare Books",
    quantity: 1,
    inventoryState: "PUBLISHED",
    isFeatured: true,
    isStaffPick: false,
    isRare: true,
    imageUrl: img("photo-1495446815901-a7297e633e8d"),
    gallery: [img("photo-1495446815901-a7297e633e8d"), img("photo-1524995997946-a1c2e315a42f")]
  },
  {
    id: "p3",
    title: "Fictional Demo: PlayStation 2 Racing Collection",
    slug: "playstation-2-racing-collection",
    category: "GAMES",
    subcategory: "PlayStation 2",
    platform: "PlayStation 2",
    publisher: "Various",
    format: "DVD case",
    ean: "5000000000030",
    sku: "BMGX-DEMO-0003",
    priceMinor: 2200,
    shortDescription: "Three fictional PS2 racing titles sold as one tested bundle.",
    description: "Fictional demo inventory. A small PlayStation 2 racing bundle with cases and discs inspected individually.",
    conditionGrade: "VERY_GOOD",
    conditionReport: "Cases show light shelf wear. Discs have fine handling marks and passed a basic boot test.",
    included: ["3 game cases", "3 discs", "2 manuals"],
    missing: ["Manual for City Sprint 2"],
    testedStatus: "Basic boot test passed",
    shelfLocation: "Games / PS2",
    quantity: 1,
    inventoryState: "PUBLISHED",
    isFeatured: true,
    isStaffPick: true,
    isRare: false,
    imageUrl: img("photo-1606144042614-b2417e99c4e3"),
    gallery: [img("photo-1606144042614-b2417e99c4e3"), img("photo-1550745165-9bc0b252726f")]
  },
  {
    id: "p4",
    title: "Fictional Demo: Boxed Indigo Handheld Console",
    slug: "boxed-indigo-handheld-console",
    category: "CONSOLES",
    subcategory: "Retro Handheld",
    platform: "Demo Portable",
    format: "Boxed console",
    sku: "BMGX-DEMO-0004",
    priceMinor: 11800,
    shortDescription: "Boxed fictional handheld console with charger and tested screen.",
    description: "Fictional demo inventory. A boxed handheld system suitable for collection or play, with visible box wear recorded.",
    conditionGrade: "GOOD",
    conditionReport: "Console shell is clean, box corners rubbed, screen has two hairline marks visible under light.",
    included: ["Console", "Box", "Charger", "Printed manual"],
    missing: [],
    testedStatus: "Powers on, buttons responsive, cartridge slot tested",
    shelfLocation: "Cabinet / Consoles",
    quantity: 1,
    inventoryState: "PUBLISHED",
    isFeatured: true,
    isStaffPick: false,
    isRare: true,
    imageUrl: img("photo-1607853202273-797f1c22a38e"),
    gallery: [img("photo-1607853202273-797f1c22a38e"), img("photo-1592840496694-26d035b52b48")]
  },
  {
    id: "p5",
    title: "Fictional Demo: Midnight Folk LP",
    slug: "midnight-folk-lp",
    category: "VINYL",
    subcategory: "Vinyl LP",
    creator: "The Northside Rooms",
    publisher: "Harbour Demo Records",
    format: "12 inch LP",
    sku: "BMGX-DEMO-0005",
    priceMinor: 1800,
    shortDescription: "Fictional folk LP with clean sleeve and visible grading notes.",
    description: "Fictional demo inventory. A boutique record-shop style listing with conservative grading.",
    conditionGrade: "VERY_GOOD",
    conditionReport: "Sleeve has one softened corner. Vinyl has light sleeve marks, visually graded only.",
    included: ["Record", "Outer sleeve", "Inner sleeve"],
    missing: [],
    shelfLocation: "Vinyl / Folk",
    quantity: 1,
    inventoryState: "PUBLISHED",
    isFeatured: true,
    isStaffPick: true,
    isRare: false,
    imageUrl: img("photo-1500530855697-b586d89ba3ee"),
    gallery: [img("photo-1500530855697-b586d89ba3ee"), img("photo-1526394931762-8a4116f6e752")]
  },
  {
    id: "p6",
    title: "Fictional Demo: Brass Compass Pendant",
    slug: "brass-compass-pendant",
    category: "JEWELLERY_CURIOSITIES",
    subcategory: "Curiosity",
    format: "Pendant",
    sku: "BMGX-DEMO-0006",
    priceMinor: 2600,
    shortDescription: "Small brass compass-style pendant with patina and working hinge.",
    description: "Fictional demo inventory. An unusual small object for the curiosities cabinet, described without unsupported age or provenance claims.",
    conditionGrade: "GOOD",
    conditionReport: "Patina throughout, hinge opens cleanly, surface marks consistent with handling.",
    included: ["Pendant"],
    missing: ["Chain"],
    shelfLocation: "Cabinet / Curiosities",
    quantity: 1,
    inventoryState: "PUBLISHED",
    isFeatured: false,
    isStaffPick: true,
    isRare: false,
    imageUrl: img("photo-1515562141207-7a88fb7ce338"),
    gallery: [img("photo-1515562141207-7a88fb7ce338"), img("photo-1602173574767-37ac01994b2a")]
  },
  {
    id: "p7",
    title: "Fictional Demo: Nintendo Nostalgia Cartridge",
    slug: "nintendo-nostalgia-cartridge",
    category: "GAMES",
    subcategory: "Retro Cartridge",
    platform: "Demo 16-bit",
    format: "Loose cartridge",
    sku: "BMGX-DEMO-0007",
    priceMinor: 3200,
    shortDescription: "Loose retro cartridge with label wear, contacts cleaned and tested.",
    description: "Fictional demo inventory. A retro game listing focused on the actual loose cartridge condition.",
    conditionGrade: "GOOD",
    conditionReport: "Label scuffing on top edge. Contacts cleaned. Shell has light yellowing.",
    included: ["Loose cartridge"],
    missing: ["Box", "Manual"],
    testedStatus: "Loaded to title screen",
    shelfLocation: "Games / Retro",
    quantity: 1,
    inventoryState: "PUBLISHED",
    isFeatured: false,
    isStaffPick: false,
    isRare: true,
    imageUrl: img("photo-1612404819070-77c6da472e68"),
    gallery: [img("photo-1612404819070-77c6da472e68"), img("photo-1493711662062-fa541adb3fc8")]
  },
  {
    id: "p8",
    title: "Fictional Demo: Crime Paperbacks Under Ten",
    slug: "crime-paperbacks-under-ten",
    category: "BOOKS",
    subcategory: "Crime & Mystery",
    creator: "Various",
    format: "Paperback bundle",
    sku: "BMGX-DEMO-0008",
    priceMinor: 800,
    shortDescription: "A rotating fictional demo bundle of three affordable crime paperbacks.",
    description: "Fictional demo inventory. A practical affordable bundle representing the everyday shelves.",
    conditionGrade: "ACCEPTABLE",
    conditionReport: "Reading creases, toned pages and shop-floor handling wear.",
    included: ["3 paperbacks"],
    missing: [],
    shelfLocation: "Books / Crime",
    quantity: 1,
    inventoryState: "PUBLISHED",
    isFeatured: false,
    isStaffPick: false,
    isRare: false,
    imageUrl: img("photo-1511108690759-009324a90311"),
    gallery: [img("photo-1511108690759-009324a90311"), img("photo-1516979187457-637abb4f9353")]
  }
];

export const demoShelves: CuratedShelf[] = [
  {
    id: "s1",
    title: "From Behind the Counter",
    slug: "from-behind-the-counter",
    introduction: "A mixed shelf of things staff would point out first: useful, odd, collectible and very Talbot Street.",
    coverImageUrl: img("photo-1524995997946-a1c2e315a42f"),
    curatorName: "Bookmart staff",
    homepageVisible: true,
    displayOrder: 1,
    productSlugs: ["the-glass-signal-signed-first-printing", "playstation-2-racing-collection", "brass-compass-pendant"],
    productNotes: {
      "the-glass-signal-signed-first-printing": "Demo signed title with careful condition notes.",
      "playstation-2-racing-collection": "A playable bundle, not just shelf dressing.",
      "brass-compass-pendant": "The kind of small object people notice in the cabinet."
    }
  },
  {
    id: "s2",
    title: "Nintendo Nostalgia",
    slug: "nintendo-nostalgia",
    introduction: "Loose cartridges, boxed handhelds and retro pieces where condition details matter.",
    coverImageUrl: img("photo-1550745165-9bc0b252726f"),
    curatorName: "Games desk",
    homepageVisible: true,
    displayOrder: 2,
    productSlugs: ["nintendo-nostalgia-cartridge", "boxed-indigo-handheld-console"],
    productNotes: {}
  },
  {
    id: "s3",
    title: "Books Under EUR 10",
    slug: "books-under-10",
    introduction: "Everyday paperbacks and Dublin reading finds that keep the shop browsable.",
    coverImageUrl: img("photo-1516979187457-637abb4f9353"),
    homepageVisible: true,
    displayOrder: 3,
    productSlugs: ["dublin-docklands-history-annotated-paperback", "crime-paperbacks-under-ten"],
    productNotes: {}
  }
];
