"use server";

import { cookies } from "next/headers";
import { redirect } from "next/navigation";
import { z } from "zod";
import { db } from "@/lib/db";
import { authCookieName } from "@/lib/auth";
import { createSignedSessionCookie, hashToken, makeRawToken } from "@/lib/session-token";
import { hashPassword, verifyPassword } from "@/lib/password";

export type AuthActionState = { ok: boolean; message: string };

const loginSchema = z.object({
  email: z.string().email(),
  password: z.string().min(8),
  next: z.string().optional()
});

export async function loginAction(_: AuthActionState, formData: FormData): Promise<AuthActionState> {
  const parsed = loginSchema.safeParse(Object.fromEntries(formData));
  if (!parsed.success) return { ok: false, message: "Enter a valid email and password." };
  const user = await db.user.findUnique({ where: { email: parsed.data.email.toLowerCase() } });
  if (!user || !verifyPassword(parsed.data.password, user.passwordHash)) return { ok: false, message: "Email or password was not recognised." };

  const rawToken = makeRawToken();
  const expiresAt = new Date(Date.now() + 1000 * 60 * 60 * 8);
  const session = await db.session.create({ data: { userId: user.id, tokenHash: hashToken(rawToken), expiresAt } });
  const cookie = await cookies();
  cookie.set(authCookieName, createSignedSessionCookie({ sessionId: session.id, userId: user.id, role: user.role, exp: expiresAt.getTime() }), {
    httpOnly: true,
    sameSite: "lax",
    secure: process.env.NODE_ENV === "production",
    expires: expiresAt,
    path: "/"
  });
  const requested = parsed.data.next || "";
  const destination =
    user.role === "ADMIN"
      ? requested.startsWith("/admin") || requested.startsWith("/staff") ? requested : "/admin"
      : user.role === "STAFF"
        ? requested.startsWith("/staff") ? requested : "/staff"
        : requested.startsWith("/account") ? requested : "/account";
  redirect(destination);
}

export async function logoutAction() {
  const cookie = await cookies();
  cookie.delete(authCookieName);
  redirect("/");
}

export async function requestPasswordReset(_: AuthActionState, formData: FormData): Promise<AuthActionState> {
  const email = z.string().email().safeParse(formData.get("email"));
  if (!email.success) return { ok: false, message: "Enter a valid email address." };
  const user = await db.user.findUnique({ where: { email: email.data.toLowerCase() } });
  if (user) {
    const token = makeRawToken();
    await db.passwordResetToken.create({ data: { userId: user.id, tokenHash: hashToken(token), expiresAt: new Date(Date.now() + 1000 * 60 * 30) } });
  }
  return { ok: true, message: "If an account exists, a reset link is generated by the configured email provider." };
}

export async function resetPassword(_: AuthActionState, formData: FormData): Promise<AuthActionState> {
  const parsed = z.object({ email: z.string().email(), password: z.string().min(8) }).safeParse(Object.fromEntries(formData));
  if (!parsed.success) return { ok: false, message: "Enter a valid email and a password of at least 8 characters." };
  await db.user.updateMany({ where: { email: parsed.data.email.toLowerCase() }, data: { passwordHash: hashPassword(parsed.data.password) } });
  return { ok: true, message: "Password updated. You can now log in." };
}
