/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as BasketRouteImport } from './routes/basket'
import { Route as SearchRouteImport } from './routes/search'
import { Route as TradeRouteImport } from './routes/trade'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as ArcadeIndexRouteImport } from './routes/arcade.index'
import { Route as ArcadeSlugRouteImport } from './routes/arcade.$slug'
import { Route as CuriosityCabinetIndexRouteImport } from './routes/curiosity-cabinet.index'
import { Route as CuriosityCabinetSlugRouteImport } from './routes/curiosity-cabinet.$slug'
import { Route as LibraryIndexRouteImport } from './routes/library.index'
import { Route as LibrarySlugRouteImport } from './routes/library.$slug'
import { Route as SoundVisionIndexRouteImport } from './routes/sound-vision.index'
import { Route as SoundVisionSlugRouteImport } from './routes/sound-vision.$slug'
import { Route as StaffIndexRouteImport } from './routes/staff.index'
import { Route as StaffStockRouteImport } from './routes/staff.stock'
import { Route as StaffTodayRouteImport } from './routes/staff.today'
import { Route as StaffAddIndexRouteImport } from './routes/staff.add.index'
import { Route as StaffAddConfirmRouteImport } from './routes/staff.add.confirm'
import { Route as StaffAddDetailsRouteImport } from './routes/staff.add.details'
import { Route as StaffAddDoneRouteImport } from './routes/staff.add.done'
import { Route as StaffAddPhotosRouteImport } from './routes/staff.add.photos'
import { Route as StaffAddScanRouteImport } from './routes/staff.add.scan'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const BasketRoute = BasketRouteImport.update({
  id: '/basket',
  path: '/basket',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const TradeRoute = TradeRouteImport.update({
  id: '/trade',
  path: '/trade',
  getParentRoute: () => rootRouteImport,
} as any)
const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const ArcadeIndexRoute = ArcadeIndexRouteImport.update({
  id: '/arcade/',
  path: '/arcade/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArcadeSlugRoute = ArcadeSlugRouteImport.update({
  id: '/arcade/$slug',
  path: '/arcade/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CuriosityCabinetIndexRoute = CuriosityCabinetIndexRouteImport.update({
  id: '/curiosity-cabinet/',
  path: '/curiosity-cabinet/',
  getParentRoute: () => rootRouteImport,
} as any)
const CuriosityCabinetSlugRoute = CuriosityCabinetSlugRouteImport.update({
  id: '/curiosity-cabinet/$slug',
  path: '/curiosity-cabinet/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryIndexRoute = LibraryIndexRouteImport.update({
  id: '/library/',
  path: '/library/',
  getParentRoute: () => rootRouteImport,
} as any)
const LibrarySlugRoute = LibrarySlugRouteImport.update({
  id: '/library/$slug',
  path: '/library/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SoundVisionIndexRoute = SoundVisionIndexRouteImport.update({
  id: '/sound-vision/',
  path: '/sound-vision/',
  getParentRoute: () => rootRouteImport,
} as any)
const SoundVisionSlugRoute = SoundVisionSlugRouteImport.update({
  id: '/sound-vision/$slug',
  path: '/sound-vision/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffIndexRoute = StaffIndexRouteImport.update({
  id: '/staff/',
  path: '/staff/',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffStockRoute = StaffStockRouteImport.update({
  id: '/staff/stock',
  path: '/staff/stock',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffTodayRoute = StaffTodayRouteImport.update({
  id: '/staff/today',
  path: '/staff/today',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffAddIndexRoute = StaffAddIndexRouteImport.update({
  id: '/staff/add/',
  path: '/staff/add/',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffAddConfirmRoute = StaffAddConfirmRouteImport.update({
  id: '/staff/add/confirm',
  path: '/staff/add/confirm',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffAddDetailsRoute = StaffAddDetailsRouteImport.update({
  id: '/staff/add/details',
  path: '/staff/add/details',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffAddDoneRoute = StaffAddDoneRouteImport.update({
  id: '/staff/add/done',
  path: '/staff/add/done',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffAddPhotosRoute = StaffAddPhotosRouteImport.update({
  id: '/staff/add/photos',
  path: '/staff/add/photos',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffAddScanRoute = StaffAddScanRouteImport.update({
  id: '/staff/add/scan',
  path: '/staff/add/scan',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/basket': typeof BasketRoute
  '/search': typeof SearchRoute
  '/trade': typeof TradeRoute
  '/wishlist': typeof WishlistRoute
  '/arcade/$slug': typeof ArcadeSlugRoute
  '/curiosity-cabinet/$slug': typeof CuriosityCabinetSlugRoute
  '/library/$slug': typeof LibrarySlugRoute
  '/sound-vision/$slug': typeof SoundVisionSlugRoute
  '/staff/stock': typeof StaffStockRoute
  '/staff/today': typeof StaffTodayRoute
  '/arcade/': typeof ArcadeIndexRoute
  '/curiosity-cabinet/': typeof CuriosityCabinetIndexRoute
  '/library/': typeof LibraryIndexRoute
  '/sound-vision/': typeof SoundVisionIndexRoute
  '/staff/': typeof StaffIndexRoute
  '/staff/add/confirm': typeof StaffAddConfirmRoute
  '/staff/add/details': typeof StaffAddDetailsRoute
  '/staff/add/done': typeof StaffAddDoneRoute
  '/staff/add/photos': typeof StaffAddPhotosRoute
  '/staff/add/scan': typeof StaffAddScanRoute
  '/staff/add/': typeof StaffAddIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/basket': typeof BasketRoute
  '/search': typeof SearchRoute
  '/trade': typeof TradeRoute
  '/wishlist': typeof WishlistRoute
  '/arcade/$slug': typeof ArcadeSlugRoute
  '/curiosity-cabinet/$slug': typeof CuriosityCabinetSlugRoute
  '/library/$slug': typeof LibrarySlugRoute
  '/sound-vision/$slug': typeof SoundVisionSlugRoute
  '/staff/stock': typeof StaffStockRoute
  '/staff/today': typeof StaffTodayRoute
  '/arcade': typeof ArcadeIndexRoute
  '/curiosity-cabinet': typeof CuriosityCabinetIndexRoute
  '/library': typeof LibraryIndexRoute
  '/sound-vision': typeof SoundVisionIndexRoute
  '/staff': typeof StaffIndexRoute
  '/staff/add/confirm': typeof StaffAddConfirmRoute
  '/staff/add/details': typeof StaffAddDetailsRoute
  '/staff/add/done': typeof StaffAddDoneRoute
  '/staff/add/photos': typeof StaffAddPhotosRoute
  '/staff/add/scan': typeof StaffAddScanRoute
  '/staff/add': typeof StaffAddIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/basket': typeof BasketRoute
  '/search': typeof SearchRoute
  '/trade': typeof TradeRoute
  '/wishlist': typeof WishlistRoute
  '/arcade/$slug': typeof ArcadeSlugRoute
  '/curiosity-cabinet/$slug': typeof CuriosityCabinetSlugRoute
  '/library/$slug': typeof LibrarySlugRoute
  '/sound-vision/$slug': typeof SoundVisionSlugRoute
  '/staff/stock': typeof StaffStockRoute
  '/staff/today': typeof StaffTodayRoute
  '/arcade/': typeof ArcadeIndexRoute
  '/curiosity-cabinet/': typeof CuriosityCabinetIndexRoute
  '/library/': typeof LibraryIndexRoute
  '/sound-vision/': typeof SoundVisionIndexRoute
  '/staff/': typeof StaffIndexRoute
  '/staff/add/confirm': typeof StaffAddConfirmRoute
  '/staff/add/details': typeof StaffAddDetailsRoute
  '/staff/add/done': typeof StaffAddDoneRoute
  '/staff/add/photos': typeof StaffAddPhotosRoute
  '/staff/add/scan': typeof StaffAddScanRoute
  '/staff/add/': typeof StaffAddIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/basket'
    | '/search'
    | '/trade'
    | '/wishlist'
    | '/arcade/$slug'
    | '/curiosity-cabinet/$slug'
    | '/library/$slug'
    | '/sound-vision/$slug'
    | '/staff/stock'
    | '/staff/today'
    | '/arcade/'
    | '/curiosity-cabinet/'
    | '/library/'
    | '/sound-vision/'
    | '/staff/'
    | '/staff/add/confirm'
    | '/staff/add/details'
    | '/staff/add/done'
    | '/staff/add/photos'
    | '/staff/add/scan'
    | '/staff/add/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/basket'
    | '/search'
    | '/trade'
    | '/wishlist'
    | '/arcade/$slug'
    | '/curiosity-cabinet/$slug'
    | '/library/$slug'
    | '/sound-vision/$slug'
    | '/staff/stock'
    | '/staff/today'
    | '/arcade'
    | '/curiosity-cabinet'
    | '/library'
    | '/sound-vision'
    | '/staff'
    | '/staff/add/confirm'
    | '/staff/add/details'
    | '/staff/add/done'
    | '/staff/add/photos'
    | '/staff/add/scan'
    | '/staff/add'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/basket'
    | '/search'
    | '/trade'
    | '/wishlist'
    | '/arcade/$slug'
    | '/curiosity-cabinet/$slug'
    | '/library/$slug'
    | '/sound-vision/$slug'
    | '/staff/stock'
    | '/staff/today'
    | '/arcade/'
    | '/curiosity-cabinet/'
    | '/library/'
    | '/sound-vision/'
    | '/staff/'
    | '/staff/add/confirm'
    | '/staff/add/details'
    | '/staff/add/done'
    | '/staff/add/photos'
    | '/staff/add/scan'
    | '/staff/add/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  BasketRoute: typeof BasketRoute
  SearchRoute: typeof SearchRoute
  TradeRoute: typeof TradeRoute
  WishlistRoute: typeof WishlistRoute
  ArcadeSlugRoute: typeof ArcadeSlugRoute
  CuriosityCabinetSlugRoute: typeof CuriosityCabinetSlugRoute
  LibrarySlugRoute: typeof LibrarySlugRoute
  SoundVisionSlugRoute: typeof SoundVisionSlugRoute
  StaffStockRoute: typeof StaffStockRoute
  StaffTodayRoute: typeof StaffTodayRoute
  ArcadeIndexRoute: typeof ArcadeIndexRoute
  CuriosityCabinetIndexRoute: typeof CuriosityCabinetIndexRoute
  LibraryIndexRoute: typeof LibraryIndexRoute
  SoundVisionIndexRoute: typeof SoundVisionIndexRoute
  StaffIndexRoute: typeof StaffIndexRoute
  StaffAddConfirmRoute: typeof StaffAddConfirmRoute
  StaffAddDetailsRoute: typeof StaffAddDetailsRoute
  StaffAddDoneRoute: typeof StaffAddDoneRoute
  StaffAddPhotosRoute: typeof StaffAddPhotosRoute
  StaffAddScanRoute: typeof StaffAddScanRoute
  StaffAddIndexRoute: typeof StaffAddIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/basket': {
      id: '/basket'
      path: '/basket'
      fullPath: '/basket'
      preLoaderRoute: typeof BasketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trade': {
      id: '/trade'
      path: '/trade'
      fullPath: '/trade'
      preLoaderRoute: typeof TradeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arcade/': {
      id: '/arcade/'
      path: '/arcade'
      fullPath: '/arcade/'
      preLoaderRoute: typeof ArcadeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arcade/$slug': {
      id: '/arcade/$slug'
      path: '/arcade/$slug'
      fullPath: '/arcade/$slug'
      preLoaderRoute: typeof ArcadeSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/curiosity-cabinet/': {
      id: '/curiosity-cabinet/'
      path: '/curiosity-cabinet'
      fullPath: '/curiosity-cabinet/'
      preLoaderRoute: typeof CuriosityCabinetIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/curiosity-cabinet/$slug': {
      id: '/curiosity-cabinet/$slug'
      path: '/curiosity-cabinet/$slug'
      fullPath: '/curiosity-cabinet/$slug'
      preLoaderRoute: typeof CuriosityCabinetSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library/': {
      id: '/library/'
      path: '/library'
      fullPath: '/library/'
      preLoaderRoute: typeof LibraryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library/$slug': {
      id: '/library/$slug'
      path: '/library/$slug'
      fullPath: '/library/$slug'
      preLoaderRoute: typeof LibrarySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sound-vision/': {
      id: '/sound-vision/'
      path: '/sound-vision'
      fullPath: '/sound-vision/'
      preLoaderRoute: typeof SoundVisionIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sound-vision/$slug': {
      id: '/sound-vision/$slug'
      path: '/sound-vision/$slug'
      fullPath: '/sound-vision/$slug'
      preLoaderRoute: typeof SoundVisionSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/': {
      id: '/staff/'
      path: '/staff'
      fullPath: '/staff/'
      preLoaderRoute: typeof StaffIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/stock': {
      id: '/staff/stock'
      path: '/staff/stock'
      fullPath: '/staff/stock'
      preLoaderRoute: typeof StaffStockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/today': {
      id: '/staff/today'
      path: '/staff/today'
      fullPath: '/staff/today'
      preLoaderRoute: typeof StaffTodayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/add/': {
      id: '/staff/add/'
      path: '/staff/add'
      fullPath: '/staff/add/'
      preLoaderRoute: typeof StaffAddIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/add/confirm': {
      id: '/staff/add/confirm'
      path: '/staff/add/confirm'
      fullPath: '/staff/add/confirm'
      preLoaderRoute: typeof StaffAddConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/add/details': {
      id: '/staff/add/details'
      path: '/staff/add/details'
      fullPath: '/staff/add/details'
      preLoaderRoute: typeof StaffAddDetailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/add/done': {
      id: '/staff/add/done'
      path: '/staff/add/done'
      fullPath: '/staff/add/done'
      preLoaderRoute: typeof StaffAddDoneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/add/photos': {
      id: '/staff/add/photos'
      path: '/staff/add/photos'
      fullPath: '/staff/add/photos'
      preLoaderRoute: typeof StaffAddPhotosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/add/scan': {
      id: '/staff/add/scan'
      path: '/staff/add/scan'
      fullPath: '/staff/add/scan'
      preLoaderRoute: typeof StaffAddScanRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  BasketRoute: BasketRoute,
  SearchRoute: SearchRoute,
  TradeRoute: TradeRoute,
  WishlistRoute: WishlistRoute,
  ArcadeSlugRoute: ArcadeSlugRoute,
  CuriosityCabinetSlugRoute: CuriosityCabinetSlugRoute,
  LibrarySlugRoute: LibrarySlugRoute,
  SoundVisionSlugRoute: SoundVisionSlugRoute,
  StaffStockRoute: StaffStockRoute,
  StaffTodayRoute: StaffTodayRoute,
  ArcadeIndexRoute: ArcadeIndexRoute,
  CuriosityCabinetIndexRoute: CuriosityCabinetIndexRoute,
  LibraryIndexRoute: LibraryIndexRoute,
  SoundVisionIndexRoute: SoundVisionIndexRoute,
  StaffIndexRoute: StaffIndexRoute,
  StaffAddConfirmRoute: StaffAddConfirmRoute,
  StaffAddDetailsRoute: StaffAddDetailsRoute,
  StaffAddDoneRoute: StaffAddDoneRoute,
  StaffAddPhotosRoute: StaffAddPhotosRoute,
  StaffAddScanRoute: StaffAddScanRoute,
  StaffAddIndexRoute: StaffAddIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
